export const archiveSections = [
  {
    slug: "publications",
    group: "研究成果",
    homeAnchor: "outcomes",
    title: "论文与著作",
    english: "PUBLICATIONS",
    description: "",
    imageLabels: ["论文封面", "方法示意图", "结果图"],
    columns: ["年份", "题目", "作者", "期刊 / 出版信息", "链接"],
  },
  {
    slug: "projects",
    group: "研究成果",
    homeAnchor: "outcomes",
    title: "科研项目",
    english: "PROJECTS",
    description: "",
    imageLabels: ["项目主图", "模型结构图", "阶段成果图"],
    columns: ["项目名称", "研究周期", "负责人", "研究方向", "项目进展"],
  },
  {
    slug: "awards",
    group: "研究成果",
    homeAnchor: "outcomes",
    title: "荣誉与获奖",
    english: "AWARDS",
    description: "",
    imageLabels: ["获奖现场照片", "证书或奖牌", "相关活动图片"],
    columns: ["时间", "奖项名称", "获奖者", "颁奖单位", "证明材料"],
  },
  {
    slug: "events",
    group: "团队动态",
    homeAnchor: "news",
    title: "学术交流与团队活动",
    english: "EVENTS",
    description: "",
    imageLabels: ["活动现场", "报告或海报", "团队合影"],
    columns: ["日期", "活动名称", "地点", "参与人员", "报道链接"],
  },
  {
    slug: "updates",
    group: "团队动态",
    homeAnchor: "news",
    title: "最新论文与研究进展",
    english: "RESEARCH UPDATES",
    description: "",
    imageLabels: ["论文封面", "研究图像", "成果展示图"],
    columns: ["日期", "成果标题", "研究方向", "简要说明", "详情链接"],
  },
  {
    slug: "more",
    group: "其他",
    homeAnchor: "other",
    title: "其他",
    english: "MORE",
    description: "",
    imageLabels: [],
    columns: ["标题", "内容", "链接"],
  },
];
